fixing yaml syntax error

diff --git a/.github/workflows/publish_docs.yml b/.github/workflows/publish_docs.yml
--- a/.github/workflows/publish_docs.yml
+++ b/.github/workflows/publish_docs.yml
@@ -14,51 +14,51 @@ jobs:
     if: github.repository == 'royerlab/dexp'
     steps:
       - name: Install Python
-          uses: actions/setup-python@v2
-          with:
-            python-version: 3.7
-      - name: Install Dependencies
-          run: |
-            python -m pip install --upgrade pip
-            python -m pip install -e .
-      - name: Run tests
-          run : |
-            python -m pytest .
-  build:
-    name: Build & Publish Docs
-    runs-on: ubuntu-latest
-    if: github.repository == 'royerlab/dexp'
-    steps:
-      - name: Install Python
-          uses: actions/setup-python@v2
-          with:
-            python-version: 3.7
-      - name: Install Dependencies
-          run: |
-            python -m pip install --upgrade pip
-            python -m pip install -e .
-            python -m pip install -r docs/requirements.txt
-      - name: Commit documentation changes
-        run: |
-          rm -rf gh-pages
-          mkdir gh-pages
-          git clone https://github.com/royerlab/dexp.git
-          cd dexp/docs/
-          ls
-          make clean
-          make html
-          cp -r build/html/* ../../gh-pages/.
-          git fetch origin
-          git checkout gh-pages
-          git config --local user.email "action@github.com"
-          git config --local user.name "GitHub Action"
-          cp -rf ../gh-pages/* .
-          git add .
-          git commit -m "Update documentation" -a || true
-          # The above command will fail if no changes were present, so we ignore
-          # the return code.
-      - name: Push changes
-        uses: ad-m/github-push-action@master
+        uses: actions/setup-python@v2
         with:
-          branch: gh-pages
-          github_token: ${{ secrets.GITHUB_TOKEN }}
+          python-version: 3.7
+      - name: Install Dependencies
+        run: |
+          python -m pip install --upgrade pip
+          python -m pip install -e .
+      - name: Run tests
+        run : |
+          python -m pytest .
+#  build:
+#    name: Build & Publish Docs
+#    runs-on: ubuntu-latest
+#    if: github.repository == 'royerlab/dexp'
+#    steps:
+#      - name: Install Python
+#          uses: actions/setup-python@v2
+#          with:
+#            python-version: 3.7
+#      - name: Install Dependencies
+#          run: |
+#            python -m pip install --upgrade pip
+#            python -m pip install -e .
+#            python -m pip install -r docs/requirements.txt
+#      - name: Commit documentation changes
+#        run: |
+#          rm -rf gh-pages
+#          mkdir gh-pages
+#          git clone https://github.com/royerlab/dexp.git
+#          cd dexp/docs/
+#          ls
+#          make clean
+#          make html
+#          cp -r build/html/* ../../gh-pages/.
+#          git fetch origin
+#          git checkout gh-pages
+#          git config --local user.email "action@github.com"
+#          git config --local user.name "GitHub Action"
+#          cp -rf ../gh-pages/* .
+#          git add .
+#          git commit -m "Update documentation" -a || true
+#          # The above command will fail if no changes were present, so we ignore
+#          # the return code.
+#      - name: Push changes
+#        uses: ad-m/github-push-action@master
+#        with:
+#          branch: gh-pages
+#          github_token: ${{ secrets.GITHUB_TOKEN }}
